sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
  - beta
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    secure: sCm0X3MKfHKwb0HqAOwyn7bSL0DXMZ4uYVZh3rNmAm9LArMaHKWQXPIuRUa21BQXT2KG2LppwXqz9YyCEpDgdBQo4umH/tp5mxIq8tGXLesNOginUq5Atk7U3CR/7NGA7bqC4Cxj+pLnpZGsS+dpm7XO2P/3qNR6coGu1qtfCEH6bMOZnn0YqIeamLsypCpT9wyrV/O26/pCZFmwc2V0Mxno0ElqF/C8ambssiBlT5dV3ydnvAMmWsoEoOGdpecd8cPw3ZL4PzlwPVPN+xuC9bBvfRpm4SxnKIEq80jMpn/FeMMUq7rUaOyts+PvjB2UwH8TE2oiZeV3XLC5VXmkjiSLz1gUL34bB9nIYPD+lOIv6MYCyFbNMKA+ZpmSPir7erNdQULIBzqrMNrG1J5OJJDnos1K3PeJ/Yh2oFJkPStOxlqmJXapDLti9FnMRl7QESnqqq4yg95uXk4/XUG8PlL/An+pHdmbEEdCgG3lDsX7fcpDs33lFr4vYvn4PYZQ55YBN0Wg8lCKo/I+Utxf/1R2coZijRkVEap6f8NYPAw2SxtayX9hNCTIbGmhCoM+wh5EMD+4enV3GqZq56aU8djsdTO3Zdeq/zIRPEbBHZ87k9hLUVpxoIfCyQlCPyZbYcgZ61WaL9llQBeLg6v0rnlILcbr/06ym/XwjXX8pcg=
